# Generated by Django 2.2.3 on 2019-08-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='contact',
            new_name='mobile_number',
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(default='Kathmandu', max_length=120),
        ),
    ]
