# Generated by Django 2.2.3 on 2019-07-31 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestemail',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
