# Generated by Django 2.2.2 on 2019-07-20 04:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20190719_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 20, 10, 16, 30, 390521)),
        ),
    ]
